"""Shared DeepSeek-Harness helpers: settings.yaml rewrite, YAML quoting, gateway patch.

Stdlib only. Safe to run as a script from bin/codex-dsh
(``$DANUS_PY $HERE/../danus/dsh.py …``) without the package on PYTHONPATH.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Optional, Tuple


def yaml_single_quoted(value: str) -> str:
    """YAML single-quoted scalar. Apostrophe -> doubled. Reject newlines/NUL."""
    if any(c in value for c in ("\n", "\r", "\x00")):
        raise ValueError("YAML scalar cannot contain newlines or NUL")
    return "'" + value.replace("'", "''") + "'"


def read_agent_default_model(text: str) -> Tuple[Optional[str], Optional[str]]:
    """(provider, model) from the first ``agent-default-model:`` block only."""
    provider: Optional[str] = None
    model: Optional[str] = None
    lines = text.splitlines()
    i = 0
    while i < len(lines):
        if lines[i].strip() == "agent-default-model:":
            i += 1
            while i < len(lines) and lines[i].startswith((" ", "\t")):
                stripped = lines[i].strip()
                if stripped.startswith("provider:"):
                    provider = stripped.split(":", 1)[1].strip()
                elif stripped.startswith("model:"):
                    model = stripped.split(":", 1)[1].strip()
                i += 1
            return provider, model
        i += 1
    return None, None


def rewrite_agent_default_model(path: Path, provider: str, model: str,
                                effort: str) -> None:
    """Replace the ``agent-default-model`` section; append one if missing."""
    try:
        text = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        text = ""
    lines = text.splitlines()
    out, i, seen = [], 0, False
    while i < len(lines):
        line = lines[i]
        if line.strip() == "agent-default-model:":
            out.append(line)
            i += 1
            while i < len(lines) and lines[i].startswith((" ", "\t")):
                i += 1
            out.append(f"  provider: {provider}")
            out.append(f"  model: {model}")
            if effort:
                out.append(f"  reasoningEffort: {effort}")
            seen = True
            continue
        out.append(line)
        i += 1
    if not seen:
        if out and out[-1] != "":
            out.append("")
        out += ["agent-default-model:", f"  provider: {provider}",
                f"  model: {model}"]
        if effort:
            out.append(f"  reasoningEffort: {effort}")
    path.write_text("\n".join(out) + "\n", encoding="utf-8")


def write_headless_gateway_patch(
    path: Path,
    *,
    role: str,
    author: str,
    project_dir: str,
    fail_on_startup: bool,
    danus_root: str,
    verify_url: str,
) -> None:
    """Write the per-run headless ``cordis.patch.yml`` with YAML-safe scalars."""
    fail = "true" if fail_on_startup else "false"
    body = "\n".join([
        "# Auto-generated by bin/codex-dsh — mounts the role-gated danus gateway.",
        "- insert:",
        "    - id: mcp-danus-gateway",
        "      name: '@deepseek-ai/dsh-mcp-client'",
        "      config:",
        "        transport: stdio",
        "        serverName: danus",
        f"        command: {yaml_single_quoted(str(Path(danus_root) / 'bin' / 'danus-mcp'))}",
        "        args: []",
        "        env:",
        f"          DANUS_ROLE: {yaml_single_quoted(role)}",
        f"          DANUS_AUTHOR: {yaml_single_quoted(author)}",
        f"          DANUS_PROJECT_DIR: {yaml_single_quoted(project_dir)}",
        f"          DANUS_VERIFY_URL: {yaml_single_quoted(verify_url)}",
        f"        cwd: {yaml_single_quoted(danus_root)}",
        "        toolCallTimeoutMs: 3600000",
        f"        failOnStartupError: {fail}",
        "",
    ])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding="utf-8")


def _cli(argv: list[str]) -> int:
    if not argv:
        print("usage: dsh.py rewrite-settings|read-agent-default-key|"
              "write-gateway-patch …", file=sys.stderr)
        return 2
    cmd, rest = argv[0], argv[1:]
    if cmd == "rewrite-settings":
        if len(rest) < 3:
            print("usage: dsh.py rewrite-settings PATH PROVIDER MODEL [EFFORT]",
                  file=sys.stderr)
            return 2
        effort = rest[3] if len(rest) > 3 else ""
        rewrite_agent_default_model(Path(rest[0]), rest[1], rest[2], effort)
        return 0
    if cmd == "read-agent-default-key":
        if len(rest) != 2 or rest[1] not in ("provider", "model"):
            print("usage: dsh.py read-agent-default-key SETTINGS.yaml provider|model",
                  file=sys.stderr)
            return 2
        try:
            text = Path(rest[0]).read_text(encoding="utf-8")
        except FileNotFoundError:
            return 0
        provider, model = read_agent_default_model(text)
        val = provider if rest[1] == "provider" else model
        if val:
            sys.stdout.write(val)
        return 0
    if cmd == "write-gateway-patch":
        p = argparse.ArgumentParser(prog="write-gateway-patch")
        p.add_argument("--out", required=True)
        p.add_argument("--role", required=True)
        p.add_argument("--author", required=True)
        p.add_argument("--project", default="")
        p.add_argument("--fail", choices=("true", "false"), required=True)
        p.add_argument("--root", required=True)
        p.add_argument("--verify-url", required=True)
        ns = p.parse_args(rest)
        write_headless_gateway_patch(
            Path(ns.out),
            role=ns.role,
            author=ns.author,
            project_dir=ns.project,
            fail_on_startup=(ns.fail == "true"),
            danus_root=ns.root,
            verify_url=ns.verify_url,
        )
        return 0
    print(f"unknown command: {cmd}", file=sys.stderr)
    return 2


def main() -> int:
    return _cli(sys.argv[1:])


if __name__ == "__main__":
    raise SystemExit(main())
